only_first: True

experiment_1:
  objects:
    - 056_tennis_ball
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 051_large_clamp
    - 052_extra_large_clamp
    - 011_banana
    - 012_strawberry
    - 016_pear
    - 025_mug
    - 006_mustard_bottle
  config:
    center: 0.45
    r: 0.1
    alpha: 1.57
    n: 1
    height: 0.51

experiment_2:
  objects:
    - 057_racquetball
    - 065-j_cups
    - 021_bleach_cleanser
    - 044_flat_screwdriver
    - 050_medium_clamp
    - 072-a_toy_airplane
  config:
    center: 0.4
    r: 0.25
    alpha: 0.78
    n: 1
    height: 0.5
