only_first: True

experiment_1:
  objects:
    - screwdriver
    - strawberry
    - pear
    - medium_clamp
    - extra_large_clamp
    - large_clamp
    - mustard_bottle
    - tennis_ball
    - banana
    - mug
  config:
    center: 0.35
    r: 0.2
    alpha: 0.785
    n: 1
    height: 0.2

# experiment_2:
#   objects:
#     - screwdriver
#     - strawberry
#     - pear
#     - medium_clamp
#     - extra_large_clamp
#     - large_clamp
#     - mustard_bottle
#     - tennis_ball
#     - banana
#     - mug
#   config:
#     center: 0.35
#     r: 0.2
#     alpha: 0.785
#     n: 1
#     height: 0.2