# enable/disable features
use_cartesian: false
over_head: false
enable_crop: true
crop_by_pixel: true
remove_noisy_ground_plane: true
angle_2d_in_cam_frame: true

# gripper/robot params
gripper_offset: 0.105
intermediate_z_stop: 0.5
scan_pose: [0.45, 0.0, 0.7, 3.14, 0.03, 0]           # scan_pose: [0.0, 0.45, 0.7, 0.0, 3.14, 3.14]
bad_grasp_z: 0.1                                    # if grasp is below this point, don't execute                    
grasp_angle_offset: 1.57

# camera params
depth_crop_size: [118, 334, 608, 1128]              # crop_size: [y_min, x_min, y_max, x_max]
pc_roi: [0.0, -0.22, -0.36, 0.7, 0.22, 0.36]        # pc_roi: [z_min, y_min, x_min, z_max, y_max, x_max]

# robot control params
robot_default_velocity: 0.1                         # As a fraction of the maximum joint velocity 
robot_approach_velocity: 0.05 

record_video: true
camera_name: "usb-046d_HD_Pro_Webcam_C920_0F85DE4F-video-index0"

# folder names
urdf_package_name: 'pick_and_place'                 # <urdf_package_name>/urdf/objects    

# coordinate frames
base_frame: 'panda_link0'
camera_frame_sim: 'panda_camera_optical_link'
camera_frame: 'camera_depth_optical_frame'

# ROS topics
grasp_in_image_frame: "grasp_service/predict"
grasp_in_camera_frame: "coords_in_cam"
grasp_in_world_frame: "predict"

cam_info_sim: '/panda_camera/rgb/camera_info'
depth_image_sim: '/panda_camera/depth/image_raw'
rgb_image_sim: '/panda_camera/rgb/image_raw'
point_cloud_sim: "/panda_camera/depth/points"

cam_info: '/camera/aligned_depth_to_color/camera_info'      # cam_info: '/camera/depth/camera_info'
point_cloud: "/camera/depth/color/points"
depth_wo_align_image: '/camera/depth/image_rect_raw'
depth_image: '/camera/aligned_depth_to_color/image_raw'
rgb_image: '/camera/color/image_raw'
point_cloud: "/camera/depth/color/points"

roi_point_cloud: "/camera/depth/color/roi_points"
depth_complete_image: '/camera/aligned_depth_to_color/depth_completed'
depth_complete_image_norm: '/camera/aligned_depth_to_color/depth_completed_norm'

visualisation: "visualisation"
cropped_depth: "cropped_depth"
cropped_rgb: "cropped_rgb"